version: '3.7'
services:

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"

  php:
    build:
      context: ./docker/php/
    volumes:
      - ./:/var/www/html
    links:
      - mariadb

  web:
    build:
      context: ./docker/apache2/
    depends_on:
      - php
      - mariadb
    volumes:
      - ./:/var/www/html/
    links:
      - php
      - mariadb
    ports:
      - "80:80"